version: "3.7"
services:
  ceryx:
    image: golang:alpine
    ports:
      - 8086:80
    env_file:
    - ./env/credentials.env
    command: ["go", "run", "ceryx"]
    volumes:
      - ../src:/go/src/