version: "3.7"
services:
  ceryx:
    build: .
    ports:
      - 8086:80
    env_file:
    - ./env/credentials.env
    command: ["go", "run", "github.com/basraven/ceryx"]
    volumes:
      - ../:/go/src/github.com/basraven/ceryx