# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ceryx-env
#   namespace: ceryx
# data:
#   credentials.env: |-
#     TELEGRAM_API_KEY=
#     CHAT_ID=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceryx
  namespace: ceryx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: ceryx
        k8s-app: ceryx
    spec:
      initContainers:
      - name: init-ceryx
        image: alpine/git
        args:
            - clone
            - --single-branch
            - --
            - https://github.com/basraven/ceryx.git
            - /go
        volumeMounts:
        - name: src
          mountPath: /go/src
      containers:
      - name: ceryx
        ports:
        - containerPort: 80
        env:
        - name: TELEGRAM_API_KEY
          value: ""
        - name: CHAT_ID
          value: ""
        image: golang:alpine
        cmd: ["go", "run", "ceryx"]
        volumeMounts:
        - name: src
          mountPath: /go/src
      volumes:
      - name: src
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: ceryx
    kubernetes.io/name: ceryx
  name: ceryx
  namespace: ceryx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: ceryx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceryx
  namespace: ceryx
spec:
  rules:
  - host: ceryx.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: ceryx
          servicePort: 80